version: '3.4'

services:
  dbMySqlDotzServer6:
    image: mysql:5.6
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - MYSQL_DATABASE=dotzdesafio
      - MYSQL_USER=dotz
      - MYSQL_PASSWORD=dotz
      - MYSQL_ROOT_PASSWORD=dotz
      - MYSQL_TCP_PORT= 3306
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
          - my-db:/var/lib/dbMySqlDotzServerD
    restart: always

  DOTZ.Desafio.API:
    image: ${DOCKER_REGISTRY-}dotzdesafioapi
    build:
      context: .
      dockerfile: DOTZ.Desafio.API/Dockerfile
    depends_on:
      - dbMySqlDotzServer6    
    ports:
      - "5000:80"
    links:
      - dbMySqlDotzServer6
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  my-db:

